### ISSUE TITLE
Local Administration takes a long time to load on Apple Silicon

### ISSUE THREAD

**Issue by dg-arboro** [dockware/dockware#138]
When opening the administration locally via http://localhost/admin, the administration just displays a white page for the first minute or so. After that, the administration is decently usable.

I couldn't figure out why this differs so much when using Apple Silicon, compared to Linux, where the administration is usable in an instant.

Specs:

MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro
Memory: 32 GB

I'm pretty sure this is a Mac problem, since I couldn't find any problems on the exact same Dockware setup on Linux or even Windows (running a subsystem).

I thought that this stems from xDebug, that's why I disabled it, but it didn't really help.

What do you need in order to investigate further?

Thanks in advance.

Edit: this occurred to me in the `dev:6.4.12.0` image, but has happened in earlier releases as well.

**Comment by boxblinkracer** [comment]
Hi

so I have good news, this is not a real problem, I'm also running it on a M1 in a really fast way :)

I think the origin might be due to bind mounting everything, could that be?
on a MAC you need to pay a bit more attention when doing this compared to Linux

here is a guide that should help you
https://docs.dockware.io/tips-and-tricks/how-to-use-bind-mounting

in general, an easy thing to figure out if that is the case, just completely turn off mounts and just "use" it.
if its then fast, then its 100% due to that mount

also...if its not because of that...i had very very weird lags since a longer time now in the admin
meaning the dropdowns were very slow and more...this also happend on server hosted administrations...
but it worked on SAFARI...so something in my chrome screwed it up...dont know what, but got a new Mac anyway, and now its working

i hope this helps

**Comment by dg-arboro** [comment]
Thank you for your response.

This seems to have resolved.
I didn't really change anything, but all of a sudden it seems pretty fast.

Thank you.

**Comment by dg-arboro** [comment]
Thank you for your suggestion. Yes, I experienced this several times, too. This seems to be a problem with Mac OS in general, though, not Docker in particular.

Either way, this issue seems to resolved and I hope this won't change any time soon.

Thanks again.

**Comment by boxblinkracer** [comment]
always happy to help :)
