### ISSUE TITLE
Mails are not sent with Shopware 5 image

### ISSUE THREAD

**Issue by Zwergal** [dockware/dockware#20]
**Describe the bug**
Using the Shopware 5.6.9 image I was not able to send Emails from the Shopsystem.
In the mailcatcher there where no Emails when I send them via Order-State change or test Emails via the backend.

**To Reproduce**
1. Run dockware with the Shopware 5.6.9 image
2. Go to the backend
3. Send an Email via the Email-Templates -> Send test Email to Shop owner
4. Nothing appears in the mailcatcher

**Expected behavior**
I would expect to see the sent Email in the mailcatcher

**Additional context**
I connected via ssh in the docker container and tried to use sendmail via the command line. With this everything works fine and the mail is shown in mailcatcher.

I tried different settings for the mailer in Shopware, but with no success.

**Comment by boxblinkracer** [comment]
Hi 

thanks for that
you are right, I just have 5.6.9 running and its not working

normally the mail configuration would need to be smtp, localhost and 1025
Still its not working with the built in mailcatcher in SW5

what should work for now, because i also have it on another system, is to use a separate mailcatcher docker image,
and use that as mailserver instead of localhost...

that would mean we "only" have a localhost smtp problem from inside SW5

thanks for letting us know

**Comment by boxblinkracer** [comment]
its no released in the v1.4 versions of the Shopware 5 images :)
thanks for creating this issue
