### ISSUE TITLE
SHOPWARE_CDN_STRATEGY_DEFAULT editable

### ISSUE THREAD

**Issue by jniclas** [dockware/dockware#30]
**Is your feature request related to a problem? Please describe.**
We copied all media files from a production server to a local dockware container, but the system didn't find the images. 
We figured out, that the production system .env file contained the env. var. SHOPWARE_CDN_STRATEGY_DEFAULT=id.
But the dockware container used the "physical_filename"-strategy by default without setting it anywhere. 
After we changed the .env file in the dockware container all images where displayed after bin/build.sh.

**Describe the solution you'd like**
Would be great to be able to set the SHOPWARE_CDN_STRATEGY_DEFAULT in a docker-compose.yml file and shopware would use it.

**Describe alternatives you've considered**
Currently we have to change the .env each time.

**Comment by boxblinkracer** [comment]
Hi

thank you for this idea

so i have a bit of a problem because its of course not shopware default, but instead a custom project thing.
and this is indeed something to think of when adding new features.

does it happen a lot to copy images into the container, and probably also restoring the database to have matching IDs - while the theme and source code is NOT used from the project? so that the rest is the standard?

because if its about running a custom project locally which is not shopware default anymore, then i would say that the .env is part of the project and thus most not be touched from dockware. (maybe you want to do a small bash setup script for your devs)

if you have the scenario, that you want to adjust the blank shopware then its indeed interesting,
but im not quite sure if this is a once in a while custom project thing on your side or a daily routine?

im just asking because we could of course add all variables over and over...but that is not the goal.
variables are normally only done if the blank shopware still works...the rest is a custom project requirement 

so could you help me a bit with the scenario, so how often, do you want to see images in blank shopware...if so, why? :D
 
 
 thank you so much
 cheers
 christian

**Comment by jniclas** [comment]
Hey,

mh I see. Indeed we created already a shell script that changes the .env in the dockware container while the import is being performed.
We will use this import-export-process for all future shopware 6 projects, as it allows us to get the state of the server with a single command on the local machine for development and debugging.  

To stay up-to-date the process will be repeated every week or so. 

Each time, the import runs on an unmodified, new and fresh dockware container to have the same result as on the server.

Summarized, its kind of default for us, but in a custom setup? So maybe you're right and its not a dockware thing :)

Best regards,
Niclas

**Comment by boxblinkracer** [comment]
Hi

yes, i would keep it like that, totally makes sense and seems to work 
so i guess we can close this one?

**Comment by jniclas** [comment]
Hey,

yes you can close the issue.

Best regards,
Niclas

**Comment by boxblinkracer** [comment]
thanks niclas
