### ISSUE TITLE
npm packages in Plugins

### ISSUE THREAD

**Issue by sawden** [dockware/dockware#8]
The `make watch-storefront` command cannot find npm packages that are imported in my custom plugin.
If i run `bin/build-storefront.sh` my Plugin build is successfull.

How do I import npm packages with "dockware/dev"?

How to reproduce the issue

1. Create a custom SW6 Plugin
2. Go to "CustomPlugin/src/Resources/app/storefront" and run `npm init`
3. Install some NPM package e.g. `npm install mapbox-gl --save`
4. Create a "webpack.config.js" in "CustomPlugin/src/Resources/app/storefront/build" and add the following lines
```javascript
// eslint-disable-next-line func-names
module.exports = function (params) {
    return {
        resolve: {
            modules: [
                `${params.basePath}Resources/app/storefront/node_modules`
            ]
        }
    };
};
```
5. Create a "src/main.js" file inside your storefront folder and import the installed npm package.
```javascript
Import mapboxgl from 'mapbox-gl';
```
6. If you use the default way with "https://github.com/shopware/development" you can "build" and "watch" the storefront without problems. Is Dockware ignoring the webpack.config.js in the Plugin directory and how can I use npm packages with dockware/dev?

Hope someone can help here 💙💜

**Comment by boxblinkracer** [comment]
Hi

ok interesting.
thanks for pointing out this problem 👍 

we'll look into it

cheers
christian

**Comment by boxblinkracer** [comment]
hey there

i've changed it to use the ./bin/watch-storefront.js script
so the official shopware script

i have to admit i haven't had time to create a custom js setup like yours 
but i had to change the command anyway,

so could you give it a try with dockware/dev:6.3.0.1 ?

if its still not working just let me know
in that case i think there might be a problem with the storefront watcher of shopware itself 
...so that it might work in another way compared to the builder

thanks
Christian
